name: 'Setup git flow'
description: 'Determine whether build and/or deploy and for which env (staging/production) depending on github event/action and target branch'
# TODO: implement inputs
# inputs:
  # production-branch:
  #   description: 'Defaults to master'
  #   required: false
  #   default: 'master'
  # staging-branch:
  #   description: 'Defaults to develop'
  #   required: false
  #   default: 'develop'
outputs:
  env:
    description: "Environment: 'Staging' or 'Production'"
    value: ${{ steps.determine.outputs.env }}
  build:
    description: "Build target: 'stage', 'prod' or 'none'"
    value: ${{ steps.determine.outputs.build }}
  deploy:
    description: "Deploy target: 'stage', 'prod' or 'none'"
    value: ${{ steps.determine.outputs.deploy }}
runs:
  using: "composite"
  steps:
    - id: determine
      run: |

        IS_PUSH="${{ github.event_name == 'push' }}"
        IS_PR="${{ github.event_name == 'pull_request' }}"
        IS_PR_SYNC="${{ github.event.action == 'synchronize' || github.event.action == 'ready_for_review' || github.event.action == 'opened' }}"
        IS_MASTER="${{ github.ref == 'refs/heads/master' }}"
        IS_MASTER_BASE="${{ github.base_ref == 'master' }}"
        IS_DEVELOP="${{ github.ref == 'refs/heads/develop' }}"
        IS_DEVELOP_BASE="${{ github.base_ref == 'develop' }}"
        IS_SYNC_STAGING="${{ contains(github.event.pull_request.labels.*.name, 'sync staging') }}"

        echo "Github event name: ${{ github.event_name }}"
        echo "Github event action name: ${{ github.event.action }}"
        echo "Github ref: ${{ github.ref }}"
        echo "Github PR base ref: ${{ github.base_ref }}"
        echo "IS_SYNC_STAGING: $IS_SYNC_STAGING"

        if [[ $IS_PR == 'true' && $IS_PR_SYNC == 'true' ]]; then
          echo "env=Staging" >> $GITHUB_OUTPUT

          if [[ $IS_MASTER_BASE == 'true' ]]; then
            echo "build=prod" >> $GITHUB_OUTPUT
          else
            echo "build=stage" >> $GITHUB_OUTPUT
          fi

          if [[ $IS_SYNC_STAGING == 'true' ]]; then
            echo "deploy=stage" >> $GITHUB_OUTPUT
          else
            echo "deploy=none" >> $GITHUB_OUTPUT
          fi

        elif [[ $IS_PUSH == 'true' ]]; then
          if [[ $IS_MASTER == 'true' ]]; then
            echo "env=Production" >> $GITHUB_OUTPUT
            echo "build=prod" >> $GITHUB_OUTPUT
            echo "deploy=prod" >> $GITHUB_OUTPUT
          elif [[ $IS_DEVELOP == 'true' ]]; then
            echo "env=Staging" >> $GITHUB_OUTPUT
            echo "build=stage" >> $GITHUB_OUTPUT
            echo "deploy=stage" >> $GITHUB_OUTPUT
          else
            echo "env=Staging" >> $GITHUB_OUTPUT
            echo "build=none" >> $GITHUB_OUTPUT
            echo "deploy=none" >> $GITHUB_OUTPUT
          fi
        else
          echo "env=Staging" >> $GITHUB_OUTPUT
          echo "build=none" >> $GITHUB_OUTPUT
          echo "deploy=none" >> $GITHUB_OUTPUT
        fi
      shell: bash

    - name: log results
      run: |
        echo "Environment: ${{ steps.determine.outputs.env }}"
        echo "Build target: ${{ steps.determine.outputs.build }}"
        echo "Deploy target: ${{ steps.determine.outputs.deploy }}"
      shell: bash
