name: 'Setup git flow'
description: 'Determine whether build and/or deploy and for which env (staging/production) depending on github event/action and target branch'
inputs:
  custom_envs:
    description: 'JSON with available environments, e.g. "{ "custom_label": "custom_env" }"'
    required: false
  production-branch:
    description: 'Defaults to main'
    required: false
    default: 'main'
  sync-staging-label-name:
    description: 'Defaults to "sync staging". Used to determine a label on current PR, and if present, deploy would be "stage"'
    required: false
    default: 'sync staging'
  labels-override:
    description: 'JSON with labels array to override current PR labels, in format of Github labels array. Useful mostly for testing'
    required: false
    default: ''
  sync-staging-on-prod:
    description: 'Whether to target env to "prod" when using "sync staging" label for PRs targeted on "main" branch. Defaults to false. If false, will keep "stage" env.'
    required: false
    default: 'false'
outputs:
  env:
    description: "Environment: 'stage' or 'prod'"
  build:
    description: "Build target: 'stage', 'prod' or 'none'"
  deploy:
    description: "Deploy target: 'stage', 'prod' or 'none'"
  sha_short:
    description: "Short SHA of current (HEAD) commit"
  branch_name:
    description: "Name of current branch"
runs:
  using: 'node16'
  main: 'dist/index.js'
